modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/Cozycord/Squish/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "CozyStudios"
description = '''
${description}
'''
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
